apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- name: quay.io/rseip/hello-world
  newTag: ad6ff540391adcbb1d4dedad3bbdba82bf4e72bd
configMapGenerator:
- name: environment-variables
  literals:
  - app=hello-world-dev
